export const ICON_VARIANTS = [
  { title: "None", value: "none" },
  { title: "Code", value: "code" },
  { title: "GitBranch", value: "git-branch" },
  { title: "List", value: "list" },
  { title: "Play", value: "play" },
  { title: "Sparkles", value: "sparkles" },
  { title: "WandSparkles", value: "wand-sparkles" },
  { title: "MessagesSquare", value: "messages-square" },
  { title: "Zap", value: "zap" },
  { title: "Infinity", value: "infinity" },
  { title: "ZoomIn", value: "zoom-in" },
  { title: "Timer", value: "timer" },
  { title: "ArrowDownToLine", value: "arrow-down-to-line" },
  { title: "ArrowUpDown", value: "arrow-up-down" },
  { title: "Redo", value: "redo" },
  { title: "Repeat", value: "repeat" },
  { title: "Scaling", value: "scaling" },
  { title: "Scan", value: "scan" },
];
