export const ICON_VARIANTS = [
  { title: "None", value: "none" },
  { title: "ArrowDownToLine", value: "arrow-down-to-line" },
  { title: "ArrowUpDown", value: "arrow-up-down" },
  { title: "Building2", value: "building-2" },
  { title: "CircleDot", value: "circle-dot" },
  { title: "Code", value: "code" },
  { title: "Compass", value: "compass" },
  { title: "ExternalLink", value: "external-link" },
  { title: "GitBranch", value: "git-branch" },
  { title: "Home", value: "home" },
  { title: "Infinity", value: "infinity" },
  { title: "Landmark", value: "landmark" },
  { title: "LayoutGrid", value: "layout-grid" },
  { title: "List", value: "list" },
  { title: "MessagesSquare", value: "messages-square" },
  { title: "Play", value: "play" },
  { title: "Redo", value: "redo" },
  { title: "Repeat", value: "repeat" },
  { title: "Scaling", value: "scaling" },
  { title: "Scan", value: "scan" },
  { title: "Sparkles", value: "sparkles" },
  { title: "Timer", value: "timer" },
  { title: "Users", value: "users" },
  { title: "WandSparkles", value: "wand-sparkles" },
  { title: "Zap", value: "zap" },
  { title: "ZoomIn", value: "zoom-in" },
];
